/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "calendar": {
    name: "calendar",
    description: "A calendar component for selecting dates.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "components/date-time-range-picker/calendar.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/date-time-range-picker/calendar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "date-input": {
    name: "date-input",
    description: "A component for inputting dates with separate fields.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "components/date-time-range-picker/date-input.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/date-time-range-picker/date-input.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "time-input": {
    name: "time-input",
    description: "A component for inputting time with hours, minutes, and AM/PM.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "components/date-time-range-picker/time-input.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/date-time-range-picker/time-input.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "date-time-input": {
    name: "date-time-input",
    description: "A component that combines date and time input.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "components/date-time-range-picker/date-time-input.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/date-time-range-picker/date-time-input.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "date-range-picker": {
    name: "date-range-picker",
    description: "A component for selecting a range of dates with presets.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "components/date-time-range-picker/date-range-picker.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/date-time-range-picker/date-range-picker.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "date-time-range-picker": {
    name: "date-time-range-picker",
    description: "A component for selecting a range of dates and times.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "components/date-time-range-picker/date-time-range-picker.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/date-time-range-picker/date-time-range-picker.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "date-range-picker-basic": {
    name: "date-range-picker-basic",
    description: "A simple date range picker with default settings.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "components/registry/examples/date-range-picker-basic.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/registry/examples/date-range-picker-basic.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "date-range-picker-with-comparison": {
    name: "date-range-picker-with-comparison",
    description: "A date range picker with comparison mode enabled.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "components/registry/examples/date-range-picker-with-comparison.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/registry/examples/date-range-picker-with-comparison.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "date-time-range-picker-basic": {
    name: "date-time-range-picker-basic",
    description: "A date time range picker for selecting dates and times.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "components/registry/examples/date-time-range-picker-basic.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/registry/examples/date-time-range-picker-basic.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  }